# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$username\
[](fg:#9A348E bg:#DA627D)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$nix_shell\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'

[directory]
style = "bg:#7A349A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[docker_context]
symbol = "docker "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#349A76"
format = '[ $symbol $branch ]($style)'

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "-"
up_to_date = "✓"
# I don't really care about stashed changes.
stashed = ""
style = "bg:#349A76"
# No space before the status because we are in the same
# "section" as the git branch.
format = '[$all_status$ahead_behind ]($style)'

[nix_shell]
style = "bg:#86BBD8"
symbol = "nix"
format = '[ $symbol ]($style)'

[time]
disabled = false
# See https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html for
# all the formats
time_format = "%X"
style = "bg:#33658A"
format = '[ $time ]($style)'
