---
name: nix

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    name: nix flake check

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18

    - name: running shellcheck on shell scripts
      run: find . -name '*flake.nix' -exec nix flake check {} \;"
