---
name: shellcheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: DeterminateSystems/nix-installer-action@v9

    - name: installing shellcheck
      # We're reusing the version from the neovim configuration so that we get expect
      # exactly the same style locally and in the CI.
      run: nix profile install ./flakes/nvim/#shellcheck

    - name: running shellcheck on shell scripts
      run: |
        files=$(find . -name '*.sh')
        IFS=$'\n'; for file in $files; do
          echo "Running shellcheck on $file"
          shellcheck "$file"
        done
