name: shellcheck

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: updating available system dependencies
      run: sudo apt-get update
    - name: installing shellcheck
      run: sudo apt-get install -y shellcheck
    - name: running shellcheck on shell scripts
      run: shellcheck scripts/*.sh
