---
name: stylua

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stylua:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: DeterminateSystems/nix-installer-action@v9

    - name: installing stylua
      # We're reusing the version from the neovim configuration so that we get expect
      # exactly the same style locally and in the CI.
      run: nix profile install ./flakes/nvim/#stylua

    - name: running stylua on lua scripts
      run: |
        files=$(find . -name '*.lua')
        IFS=$'\n'; for file in $files; do
          echo "Running stylua on $file"
          stylua --check "$file"
        done
